-- --------------------------------------------------------
-- Host:                         85.208.23.50
-- Versión del servidor:         10.3.37-MariaDB-0ubuntu0.20.04.1 - Ubuntu 20.04
-- SO del servidor:              debian-linux-gnu
-- HeidiSQL Versión:             12.8.0.6908
-- --------------------------------------------------------

/*!40101 SET @OLD_CHARACTER_SET_CLIENT=@@CHARACTER_SET_CLIENT */;
/*!40101 SET NAMES utf8 */;
/*!50503 SET NAMES utf8mb4 */;
/*!40103 SET @OLD_TIME_ZONE=@@TIME_ZONE */;
/*!40103 SET TIME_ZONE='+00:00' */;
/*!40014 SET @OLD_FOREIGN_KEY_CHECKS=@@FOREIGN_KEY_CHECKS, FOREIGN_KEY_CHECKS=0 */;
/*!40101 SET @OLD_SQL_MODE=@@SQL_MODE, SQL_MODE='NO_AUTO_VALUE_ON_ZERO' */;
/*!40111 SET @OLD_SQL_NOTES=@@SQL_NOTES, SQL_NOTES=0 */;


-- Volcando estructura de base de datos para ENVIO_PRECIOS_MITYC
CREATE DATABASE IF NOT EXISTS `ENVIO_PRECIOS_MITYC` /*!40100 DEFAULT CHARACTER SET utf8 COLLATE utf8_general_ci */;
USE `ENVIO_PRECIOS_MITYC`;

-- Volcando estructura para tabla ENVIO_PRECIOS_MITYC.EMPRESAS
CREATE TABLE IF NOT EXISTS `EMPRESAS` (
  `CODIGO` int(11) NOT NULL AUTO_INCREMENT,
  `EMPRESA` varchar(50) CHARACTER SET utf8mb4 COLLATE utf8mb4_general_ci NOT NULL,
  `IP` varchar(50) CHARACTER SET utf8mb4 COLLATE utf8mb4_general_ci NOT NULL,
  `PUERTO` varchar(50) NOT NULL DEFAULT '0',
  PRIMARY KEY (`CODIGO`) USING BTREE
) ENGINE=InnoDB AUTO_INCREMENT=9 DEFAULT CHARSET=utf8 COLLATE=utf8_general_ci;

-- Volcando estructura para tabla ENVIO_PRECIOS_MITYC.ESTABLECIMIENTOS_EMPRESA
CREATE TABLE IF NOT EXISTS `ESTABLECIMIENTOS_EMPRESA` (
  `CODIGO_EESS` int(11) NOT NULL,
  `CODIGO_EMPRESA` int(11) NOT NULL,
  PRIMARY KEY (`CODIGO_EESS`,`CODIGO_EMPRESA`),
  KEY `FK__EMPRESAS` (`CODIGO_EMPRESA`),
  CONSTRAINT `FK__EMPRESAS` FOREIGN KEY (`CODIGO_EMPRESA`) REFERENCES `EMPRESAS` (`CODIGO`) ON DELETE CASCADE ON UPDATE CASCADE,
  CONSTRAINT `FK__MITYC_ESTABLECIMIENTOS` FOREIGN KEY (`CODIGO_EESS`) REFERENCES `MITYC_ESTABLECIMIENTOS` (`ID_EESS_MITYC`) ON DELETE CASCADE ON UPDATE CASCADE
) ENGINE=InnoDB DEFAULT CHARSET=utf8 COLLATE=utf8_general_ci;

-- Volcando estructura para tabla ENVIO_PRECIOS_MITYC.MITYC_ESTABLECIMIENTOS
CREATE TABLE IF NOT EXISTS `MITYC_ESTABLECIMIENTOS` (
  `ID_EESS_MITYC` int(11) NOT NULL,
  `CODIGO_MUNICIPIO` int(11) NOT NULL,
  `NOMBRE_ESTABLECIMIENTO` varchar(100) NOT NULL DEFAULT '',
  `CODIGO_TERMINAL` varchar(100) DEFAULT NULL,
  `ESTADO` int(1) NOT NULL DEFAULT 1,
  PRIMARY KEY (`ID_EESS_MITYC`,`CODIGO_MUNICIPIO`),
  KEY `ID_EESS_MITYC` (`ID_EESS_MITYC`),
  KEY `FK_MITYC_ESTABLECIMIENTOS_MITYC_MUNICIPIOS` (`CODIGO_MUNICIPIO`),
  CONSTRAINT `FK_MITYC_ESTABLECIMIENTOS_MITYC_MUNICIPIOS` FOREIGN KEY (`CODIGO_MUNICIPIO`) REFERENCES `MITYC_MUNICIPIOS` (`CODIGO`) ON DELETE CASCADE ON UPDATE CASCADE
) ENGINE=InnoDB DEFAULT CHARSET=utf8 COLLATE=utf8_general_ci;


-- Volcando estructura para tabla ENVIO_PRECIOS_MITYC.MITYC_MUNICIPIOS
CREATE TABLE IF NOT EXISTS `MITYC_MUNICIPIOS` (
  `CODIGO` int(11) NOT NULL DEFAULT 0,
  `NOMBRE` varchar(100) CHARACTER SET utf8mb4 COLLATE utf8mb4_general_ci DEFAULT NULL,
  PRIMARY KEY (`CODIGO`) USING BTREE
) ENGINE=InnoDB DEFAULT CHARSET=utf8 COLLATE=utf8_general_ci;

-- Volcando datos para la tabla ENVIO_PRECIOS_MITYC.MITYC_MUNICIPIOS: ~43 rows (aproximadamente)
DELETE FROM `MITYC_MUNICIPIOS`;
INSERT INTO `MITYC_MUNICIPIOS` (`CODIGO`, `NOMBRE`) VALUES
	(40, 'Salvatierra/Agurain'),
	(395, 'Ávila'),
	(644, 'Badajoz'),
	(712, 'Mérida'),
	(875, 'Badalona'),
	(881, 'Barcelona'),
	(933, 'Collbató'),
	(940, 'Esparreguera'),
	(1011, 'Olesa de Montserrat'),
	(1025, 'Parets del Vallès'),
	(1058, 'Sant Andreu de la Barca'),
	(1070, 'Sant Esteve Sesrovires'),
	(1155, 'Vallirana'),
	(1185, 'Aranda de Duero'),
	(1568, 'Belvís de Monroy'),
	(1769, 'Barrios (Los)'),
	(2031, 'Valdepeñas'),
	(2392, 'Tébar'),
	(2538, 'Llers'),
	(2574, 'Pont de Molins'),
	(2726, 'Darro'),
	(2743, 'Gor'),
	(2766, 'Láchar'),
	(2887, 'Cabanillas del Campo'),
	(3161, 'Elgoibar'),
	(3176, 'Irun'),
	(3191, 'Oiartzun'),
	(3506, 'Bailén'),
	(3605, 'Bembibre'),
	(3896, 'Granyanella'),
	(3916, 'Lleida'),
	(4354, 'Madrid'),
	(4690, 'Egüés'),
	(5317, 'Salvaterra de Miño'),
	(5322, 'Tui'),
	(5603, 'Sancti-Spíritus'),
	(6076, 'Campana (La)'),
	(6153, 'Valencina de la Concepción'),
	(6594, 'Cella'),
	(6841, 'Illescas'),
	(7177, 'Riba-roja de Túria'),
	(7215, 'Vallada'),
	(7410, 'Valladolid'),
	(7455, 'Zaratán'),
	(7588, 'Benavente'),
	(7944, 'La Joyosa');

-- Volcando estructura para tabla ENVIO_PRECIOS_MITYC.MITYC_PRECIOS
CREATE TABLE IF NOT EXISTS `MITYC_PRECIOS` (
  `CODIGO_EESS` int(11) NOT NULL,
  `ID_MUNICIPIO` int(11) NOT NULL,
  `CODIGO_PRODUCTO` varchar(50) NOT NULL,
  `CODIGO_PRODUCTO_CA` int(11) NOT NULL,
  `PRECIO` varchar(50) DEFAULT NULL,
  `FECHA_UPD` datetime NOT NULL,
  `FETCH_DATE` datetime NOT NULL,
  PRIMARY KEY (`CODIGO_EESS`,`ID_MUNICIPIO`,`CODIGO_PRODUCTO`,`CODIGO_PRODUCTO_CA`),
  KEY `CODIGO_EESS` (`CODIGO_EESS`),
  KEY `ID_MUNICIPIO` (`ID_MUNICIPIO`),
  KEY `CODIGO_PRODUCTO` (`CODIGO_PRODUCTO`),
  KEY `CODIGO_PRODUCTO_CA` (`CODIGO_PRODUCTO_CA`),
  CONSTRAINT `FK_MITYC_PRECIOS_MITYC_ESTABLECIMIENTOS` FOREIGN KEY (`CODIGO_EESS`) REFERENCES `MITYC_ESTABLECIMIENTOS` (`ID_EESS_MITYC`) ON DELETE CASCADE ON UPDATE CASCADE,
  CONSTRAINT `FK_MITYC_PRECIOS_MITYC_MUNICIPIOS` FOREIGN KEY (`ID_MUNICIPIO`) REFERENCES `MITYC_MUNICIPIOS` (`CODIGO`) ON DELETE CASCADE ON UPDATE CASCADE,
  CONSTRAINT `FK_MITYC_PRECIOS_MITYC_PRODUCTOS` FOREIGN KEY (`CODIGO_PRODUCTO`) REFERENCES `MITYC_PRODUCTOS` (`CODIGO`) ON DELETE CASCADE ON UPDATE CASCADE,
  CONSTRAINT `FK_MITYC_PRECIOS_MITYC_PRODUCTOS_2` FOREIGN KEY (`CODIGO_PRODUCTO_CA`) REFERENCES `MITYC_PRODUCTOS` (`CODIGO_CA`) ON DELETE CASCADE ON UPDATE CASCADE
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4 COLLATE=utf8mb4_general_ci;

-- Volcando estructura para tabla ENVIO_PRECIOS_MITYC.MITYC_PRECIOS_ENVIO
CREATE TABLE IF NOT EXISTS `MITYC_PRECIOS_ENVIO` (
  `CODIGO_EESS` int(11) NOT NULL,
  `CODIGO_EMPRESA` int(11) NOT NULL,
  `CODIGO_PRODUCTO_CA` int(11) NOT NULL,
  `PRECIO` varchar(50) NOT NULL,
  `ESTADO` int(11) NOT NULL DEFAULT 2,
  `FECHA_ENVIO` datetime DEFAULT NULL,
  `FECHA_INS` datetime NOT NULL,
  `INTENTOS_ENVIO` int(11) NOT NULL DEFAULT 0,
  `ANULADO` tinyint(4) DEFAULT 0,
  PRIMARY KEY (`CODIGO_EESS`,`CODIGO_EMPRESA`,`CODIGO_PRODUCTO_CA`,`FECHA_INS`),
  KEY `FK_MITYC_PRECIOS_ENVIO_EMPRESAS` (`CODIGO_EMPRESA`),
  KEY `FK_MITYC_PRECIOS_ENVIO_MITYC_PRODUCTOS` (`CODIGO_PRODUCTO_CA`),
  KEY `FECHA_INS` (`FECHA_INS`),
  CONSTRAINT `FK_MITYC_PRECIOS_ENVIO_EMPRESAS` FOREIGN KEY (`CODIGO_EMPRESA`) REFERENCES `EMPRESAS` (`CODIGO`) ON DELETE CASCADE ON UPDATE CASCADE,
  CONSTRAINT `FK_MITYC_PRECIOS_ENVIO_MITYC_ESTABLECIMIENTOS` FOREIGN KEY (`CODIGO_EESS`) REFERENCES `MITYC_ESTABLECIMIENTOS` (`ID_EESS_MITYC`) ON DELETE CASCADE ON UPDATE CASCADE,
  CONSTRAINT `FK_MITYC_PRECIOS_ENVIO_MITYC_PRODUCTOS` FOREIGN KEY (`CODIGO_PRODUCTO_CA`) REFERENCES `MITYC_PRODUCTOS` (`CODIGO_CA`) ON DELETE CASCADE ON UPDATE CASCADE
) ENGINE=InnoDB DEFAULT CHARSET=utf8 COLLATE=utf8_general_ci;

-- Volcando estructura para tabla ENVIO_PRECIOS_MITYC.MITYC_PRODUCTOS
CREATE TABLE IF NOT EXISTS `MITYC_PRODUCTOS` (
  `CODIGO` varchar(100) CHARACTER SET utf8mb4 COLLATE utf8mb4_general_ci NOT NULL,
  `CODIGO_CA` int(11) NOT NULL,
  `NOMBRE` varchar(50) CHARACTER SET utf8mb4 COLLATE utf8mb4_general_ci NOT NULL,
  PRIMARY KEY (`CODIGO`,`CODIGO_CA`) USING BTREE,
  KEY `CODIGO_CA` (`CODIGO_CA`)
) ENGINE=InnoDB DEFAULT CHARSET=utf8 COLLATE=utf8_general_ci;

-- Volcando estructura para tabla ENVIO_PRECIOS_MITYC.PRODUCTOS_ESTABLECIMIENTOS
CREATE TABLE IF NOT EXISTS `PRODUCTOS_ESTABLECIMIENTOS` (
  `CODIGO_EESS` int(11) NOT NULL,
  `CODIGO_PRODUCTO` varchar(100) CHARACTER SET utf8mb4 COLLATE utf8mb4_general_ci NOT NULL,
  PRIMARY KEY (`CODIGO_EESS`,`CODIGO_PRODUCTO`),
  KEY `CODIGO_PRODUCTO` (`CODIGO_PRODUCTO`),
  KEY `CODIGO_EESS` (`CODIGO_EESS`),
  CONSTRAINT `FK_PRODUCTOS_ESTABLECIMIENTOS_MITYC_ESTABLECIMIENTOS` FOREIGN KEY (`CODIGO_EESS`) REFERENCES `MITYC_ESTABLECIMIENTOS` (`ID_EESS_MITYC`) ON DELETE CASCADE ON UPDATE CASCADE,
  CONSTRAINT `FK_PRODUCTOS_ESTABLECIMIENTOS_MITYC_PRODUCTOS` FOREIGN KEY (`CODIGO_PRODUCTO`) REFERENCES `MITYC_PRODUCTOS` (`CODIGO`) ON DELETE CASCADE ON UPDATE CASCADE
) ENGINE=InnoDB DEFAULT CHARSET=utf8 COLLATE=utf8_general_ci;

-- Volcando estructura para tabla ENVIO_PRECIOS_MITYC.USUARIOS
CREATE TABLE IF NOT EXISTS `USUARIOS` (
  `ID` int(11) NOT NULL AUTO_INCREMENT,
  `USUARIO` varchar(50) NOT NULL,
  `PASSWORD` varchar(100) NOT NULL,
  PRIMARY KEY (`ID`)
) ENGINE=InnoDB AUTO_INCREMENT=2 DEFAULT CHARSET=utf8 COLLATE=utf8_general_ci;

-- Volcando datos para la tabla ENVIO_PRECIOS_MITYC.USUARIOS: ~0 rows (aproximadamente)
DELETE FROM `USUARIOS`;
INSERT INTO `USUARIOS` (`ID`, `USUARIO`, `PASSWORD`) VALUES
	(1, 'efidata', '$2y$10$YZAIVx/lL36DntaZGFeLFeELxEUodgFgGXbcZrSaucVAYK1EGu3By');

/*!40103 SET TIME_ZONE=IFNULL(@OLD_TIME_ZONE, 'system') */;
/*!40101 SET SQL_MODE=IFNULL(@OLD_SQL_MODE, '') */;
/*!40014 SET FOREIGN_KEY_CHECKS=IFNULL(@OLD_FOREIGN_KEY_CHECKS, 1) */;
/*!40101 SET CHARACTER_SET_CLIENT=@OLD_CHARACTER_SET_CLIENT */;
/*!40111 SET SQL_NOTES=IFNULL(@OLD_SQL_NOTES, 1) */;
